name: Downstream integration build (GeoServer)

on:
  # trigger on PR, but only on main branch, the checkouts of the downstream projects are also targeting main (default branch)
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - uses: actions/checkout@v4
    - name: Maven repository caching
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: gwc-integration-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          integration-${{ runner.os }}-maven-
    - name: Build GeoWebCache (no tests, prepare fresh artifacts)
      run: mvn -B clean install -T2 -Dall --file geowebcache/pom.xml -DskipTests
    - name: Checkout GeoServer
      run: |
        cd ~
        echo "Preparing git ssh checkouts"
        mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        echo "Checking out GeoServer"
        mkdir geoserver
        git clone https://github.com/geoserver/geoserver.git geoserver
    - name: Build GeoServer with tests
      run: |
        export MAVEN_OPTS="-Xmx512m $TEST_OPTS -XX:+UseStringDeduplication -XX:+UseG1GC -XX:MaxHeapFreeRatio=30 -XX:MinHeapFreeRatio=10"
        cd ~
        mvn -B -f geoserver/src/pom.xml install -nsu -Prelease -Dspotless.apply.skip=true -DskipTests
        mvn -B -f geoserver/src/community/pom.xml install -nsu -DcommunityRelease -Dspotless.apply.skip=true -DskipTests
        mvn -B -f geoserver/src/pom.xml test -T2 -nsu -Djvm.opts="$TEST_OPTS" -Prelease -Dspotless.apply.skip=true
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {} 
